#!/usr/bin/python

import sys
import dbus

if (len(sys.argv) < 2):
	print "Usage: %s <dbus message path>" % (sys.argv[0])
	sys.exit(1)

bus = dbus.SessionBus()

message = dbus.Interface(bus.get_object('org.ofono.mms', sys.argv[1]),
					'org.ofono.mms.Message')

message.Delete()
