#!/usr/bin/python

import dbus

bus = dbus.SessionBus()

manager = dbus.Interface(bus.get_object('org.ofono.mms', '/org/ofono/mms'),
						'org.ofono.mms.Manager')

services = manager.GetServices()

for path, properties in services:
	print "[ %s ]" % (path)

	object = dbus.Interface(bus.get_object('org.ofono.mms', path),
						'org.ofono.mms.Service')

	try:
		properties = object.GetProperties()
	except:
		continue

	for key in properties.keys():
		val = str(properties[key])
		print "        %s = %s" % (key, val)

	print
