#!/bin/sh

for i in $*
do
	echo "extern struct mms_plugin_desc __mms_builtin_$i;"
done

echo
echo "static struct mms_plugin_desc *__mms_builtin[] = {"

for i in $*
do
	echo "  &__mms_builtin_$i,"
done

echo "  NULL"
echo "};"
